### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by martinthomson** [chrisdavidmills/push-api-demo#4]
So that the node dependencies don't need to be explicitly installed, with package.json you only have to run `npm install`

**Comment by chrisdavidmills** [comment]
This sounds like a good idea, but I don't have time to learn this right now. I'll consider this for future additions.

**Comment by martinthomson** [comment]
Don't just close it, the contents need only include this:

```json
{ "name": "push-demo", "version": "0.0.1", "dependencies": { "web-push": "0.0.*" } }
```

of course, you could add extras: https://docs.npmjs.com/files/package.json
